### PR TITLE
Migrate sdk

### PR DESCRIPTION
**Pull request by gavinfish**
Recreate #69 to enable incremental build and generate a RC package.

### CODE REVIEW

**Comment by gavinfish** [comment]
@runzexia the RC package is available now at [1.0.1-rc127.957e031e8dfa](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/kubernetes-cd/1.0.1-rc127.957e031e8dfa/).

**Comment by tkuther** [comment]
> @runzexia the RC package is available now at [1.0.1-rc127.957e031e8dfa](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/kubernetes-cd/1.0.1-rc127.957e031e8dfa/).

Tried the RC (with Jenkins 2.176.2)
```
java.lang.LinkageError: loader constraint violation: loader (instance of hudson/ClassicPluginStrategy$AntClassLoader2) previously initiated loading for a different type with name "com/google/common/collect/ImmutableSet"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:707)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1363)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.common.reflect.ClassPath$Scanner.<init>(ClassPath.java:328)
	at com.google.common.reflect.ClassPath$DefaultScanner.<init>(ClassPath.java:455)
	at com.google.common.reflect.ClassPath.from(ClassPath.java:96)
	at io.kubernetes.client.util.Yaml.initModelMap(Yaml.java:118)
	at io.kubernetes.client.util.Yaml.<clinit>(Yaml.java:136)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.initModelMap(DeploymentCommand.java:140)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.<clinit>(DeploymentCommand.java:91)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.microsoft.jenkins.azurecommons.command.CommandService.ensureCreation(CommandService.java:126)
	at com.microsoft.jenkins.azurecommons.command.CommandService.access$100(CommandService.java:23)
	at com.microsoft.jenkins.azurecommons.command.CommandService$Builder.withSingleCommand(CommandService.java:198)
	at com.microsoft.jenkins.kubernetes.KubernetesDeployContext.configure(KubernetesDeployContext.java:88)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:41)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gavinfish** [comment]
@tkuther nice shot! The exception is thrown in pipeline project. I have committed a fix for it. You can get the new RC version in the `All checks have passed` details' `incrementals` once the CI job finishes. Feel free to give any feedback.

**Comment by tkuther** [comment]
@gavinfish looks good now, thanks! Will do some more testing over the day..

**Comment by gavinfish** [comment]
@tkuther any update here? @runzexia I think it is time for us to make this a public release. Any potential risks which will block existing users?

**Comment by runzexia** [comment]
> @tkuther any update here? @runzexia I think it is time for us to make this a public release. Any potential risks which will block existing users?

I think the potential risks may have the kind of problems @tkuther encountered, and I agree that it can be released now.

**Comment by tkuther** [comment]
@runzexia & @gavinfish we have been running the latest rc build in our integration environment without any issues so far. Also tested previously unsupported resources like PersistentVolumeClaim successfully.

Deployment jobs are multibranch pipelines with docker build and kubernetes deploy steps wrapped in shared library vars.
k8s version is 1.14.3.

**Pull request merged**
