### PR TITLE
Add CronJob and HPA support

### LINKED ISSUE #27: Null Pointer Exception on deploying a cronjob
Hello,

when I try to deploy a cronjob I get the following error: 

```
Loading configuration: /home/jenkins/workspace/services_jenkins-test-XO46LEN76A4SRY5UHHB7TIJEC6LPJOOXXGO4K2VO2S7KI32P6WFQ/.kube/services-cron.yml
ERROR: ERROR: null
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:286)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:278)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:65)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:134)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:102)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:66)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-10-40-0-0.eu-central-1.compute.internal/10.40.0.0:55726
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at hudson.FilePath.act(FilePath.java:1093)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:66)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Kubernetes deployment ended with HasError
```

Not sure if they are meant to be working, the README only lists jobs, would be great if they would be supported though! Thanks for your help in advance. The yaml looks like this:

```YAML
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: services-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: env
              secret:
                secretName: env
                items:
                - key: env_file
                  path: .env
          containers:
          - name: services-worker
            image: "kiron/services:${BRANCH_NAME}-${BUILD_ID}"
            args:
            - /bin/bash
            - -c
            - /services/cron-startup.sh
            volumeMounts:
              - name: env
                mountPath: /var/www/html/services/internal-october/.env
                subPath: .env
                readOnly: true
              - name: env
                mountPath: /var/www/html/services/api/.env
                subPath: .env
                readOnly: true
          restartPolicy: OnFailure

```

Sidenotes: Applying the yaml with kubectl directly works and the containers and volume mounts are used in a deployment and also work fine.

### LINKED ISSUE #50: apps/v1 for deployments not supported
Looks like `extensions/v1beta1` is still expected for Deployments. When using `apps/v1`, the following error is shown for AKS deployments:

`o.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xxxx.hcp.eastus.azmk8s.io/apis/extensions/v1beta1/namespaces/default/deployments. Message: the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).`

Extract from deployment file:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:`

Deployment to this cluster with `apps/v1` kubectl works without issues.
Deployment to this cluster with `extensions/v1beta1` and kubernetes-cd-plugin+azure-acs-plugin works without issues.

### LINKED ISSUE #61: Skipped unsupported resource: HorizontalPodAutoscale
Trying to use this resource (HPA) in kubernetesDeploy and fails to do so. Does this plugin not support the latter concepts? Is there a workaround?

### PR DESCRIPTION
**Pull request by dabeck**
This adds the ability to deploy kubernetes cronJobs and horizontalPodAutoscaler.
This resolves #27, resolves #50 and resolves #61

### CODE REVIEW

**Comment by jiang-wei** [comment]
waiting for CronJob support :)

**Comment by dabeck** [comment]
While you are waiting for the merge you could actually download the snapshot build Here: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fkubernetes-cd-plugin/detail/PR-68/3/artifacts
and install it manually.

**Comment by jiang-wei** [comment]
Message: the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1).

so the API version changed?

I have to recreate every deployment...

**Comment by jiang-wei** [comment]
any hope get it merged?

**Comment by grazius** [comment]
Hello this merge request can be merge ?

**Comment by joandyiglesias** [comment]
Applying this patch breaks existing extensions/v1beta1 definitions. Also, the new HPA definition only seem to work for https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#horizontalpodautoscaler-v1-autoscaling and not https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#horizontalpodautoscaler-v2beta1-autoscaling.

**Comment by stefanmcshane** [comment]
Any update on merging this?

**Comment by gavinfish** [comment]
This PR looks good to me. But for the fabric8 SDK not supporting the legacy API version, at least we should point out the version of Kubernetes we support after this merge.

**Pull request merged**
